import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { personal as englishPersonal } from "./data/personal.js";
import { navLinks as englishNavLinks } from "./data/navigation.js";
import { education as englishEducation } from "./data/education.js";
import { experience as englishExperience } from "./data/experience.js";
import { skillGroups as englishSkillGroups } from "./data/skills.js";
import { projects as englishProjects } from "./data/projects.js";
const en = { aboutLabel:"About Me", aboutTitle:"Securing the digital frontier, one layer at a time.", educationLabel:"Education", educationTitle:"Academic Background", experienceLabel:"Experience", experienceTitle:"Professional Journey", projectsLabel:"Projects", projectsTitle:"Selected Work", projectsIntro:"End-to-end cybersecurity and cloud engineering projects — from honeypot infrastructure to full SIEM deployments.", skillsLabel:"Skills", skillsTitle:"Technical Expertise", skillsIntro:"A snapshot of the tools and technologies I work with across security, cloud, and automation.", certificationsLabel:"Certifications", certificationsTitle:"Credentials & Learning", contactLabel:"Contact", contactTitle:"Let's Connect", contactIntro:"Open to cybersecurity, cloud security, and DevSecOps roles. Reach out anytime.", downloadCv:"↓ Download CV", contactMe:"Contact Me →", contact:"Contact", viewDetails:"View Details →", viewCertificate:"View certificate", close:"Close", project:"Project", overview:"Overview", challenges:"Challenges", results:"Results", technologies:"Technologies", credential:"View credential ↗", sendMessage:"Send Message →", messageReceived:"Message received!", response:"I'll get back to you as soon as possible.", name:"NAME", email:"EMAIL", message:"MESSAGE", yourName:"Your name", yourMessage:"Your message...", phone:"Phone", language:"Français" };
const fr = { aboutLabel:"À propos", aboutTitle:"Sécuriser la frontière numérique, une couche à la fois.", educationLabel:"Formation", educationTitle:"Parcours académique", experienceLabel:"Expérience", experienceTitle:"Parcours professionnel", projectsLabel:"Projets", projectsTitle:"Réalisations sélectionnées", projectsIntro:"Projets de cybersécurité et d’ingénierie cloud, de l’infrastructure de honeypot aux déploiements SIEM complets.", skillsLabel:"Compétences", skillsTitle:"Expertise technique", skillsIntro:"Un aperçu des outils et technologies que j’utilise en sécurité, cloud et automatisation.", certificationsLabel:"Certifications", certificationsTitle:"Certifications et apprentissage", contactLabel:"Contact", contactTitle:"Restons en contact", contactIntro:"Ouverte aux postes en cybersécurité, sécurité cloud et DevSecOps. N’hésitez pas à me contacter.", downloadCv:"↓ Télécharger le CV", contactMe:"Me contacter →", contact:"Contact", viewDetails:"Voir les détails →", viewCertificate:"Voir le certificat", close:"Fermer", project:"Projet", overview:"Aperçu", challenges:"Défis", results:"Résultats", technologies:"Technologies", credential:"Voir le certificat ↗", sendMessage:"Envoyer le message →", messageReceived:"Message reçu !", response:"Je vous répondrai dès que possible.", name:"NOM", email:"E-MAIL", message:"MESSAGE", yourName:"Votre nom", yourMessage:"Votre message...", phone:"Téléphone", language:"English" };
const frenchPersonal = { ...englishPersonal, title:"Ingénieure en cybersécurité", subtitle:"Passionnée par le cloud et le DevSecOps", tagline:"Concevoir des infrastructures cloud sécurisées, automatiser les déploiements et explorer les solutions de cybersécurité modernes.", status:"À l’écoute d’opportunités", interests:[{icon:"🛡️",label:"Sécurité cloud",desc:"Concevoir des architectures cloud sécurisées par défaut sur AWS et OpenStack"},{icon:"⚙️",label:"DevSecOps",desc:"Intégrer la sécurité à chaque étape de la chaîne CI/CD"},{icon:"🔍",label:"Détection des menaces",desc:"Créer des pipelines SIEM avec réponse automatisée aux incidents"},{icon:"🤖",label:"IA × Cybersécurité",desc:"Appliquer le machine learning à la classification et à la détection d’anomalies"}], bio:["Diplômée en ingénierie de la cybersécurité, je suis spécialisée dans la sécurité cloud, le DevSecOps et l’automatisation des infrastructures. Mon parcours couvre la conception d’architectures sécurisées, la conteneurisation de solutions de sécurité et l’intégration du renseignement sur les menaces dans des environnements cloud modernes.","J’aime expérimenter les technologies de cybersécurité, du déploiement de honeypots auto-résilients sur AWS à la création de pipelines SIEM cloud-native avec réponse automatisée aux incidents. Je recherche des opportunités pour repousser les limites de l’ingénierie cloud sécurisée."] };
const frenchNav = ["À propos","Formation","Expérience","Projets","Compétences","Certifications","Contact"];
const frenchTitles = ["Plateforme de microservices cloud-native pour événements sportifs","Plateforme d’automatisation d’infrastructure Kubernetes sécurisée","Honeypot auto-résilient sur AWS","Déploiement automatisé d’application AWS","Déploiement d’un cloud privé avec OpenStack","Pipeline SIEM cloud-native avec renseignement sur les menaces","Laboratoire de virtualisation VMware ESXi et vCenter Server","SecureOps Lab — laboratoire virtuel de cybersécurité","HardenedHost — durcissement Linux as Code (basé ANSSI)"];
const frenchShorts = ["Plateforme de microservices prête pour la production, avec Kubernetes, GitOps, DevSecOps et observabilité complète.","Plateforme Kubernetes prête pour la production avec Infrastructure as Code, GitOps, sécurité d’exécution et observabilité.","Honeypot résilient qui se rétablit automatiquement et envoie les données d’attaquants vers S3.","Pipeline de déploiement Flask hautement disponible sur AWS avec Terraform, Ansible et Packer.","Cloud privé sur site avec OpenStack/DevStack : calcul, réseau, stockage, identité, conteneurs et déploiement automatisé.","Pipeline SIEM automatisé reliant la détection AWS à TheHive, Cortex et MISP pour le triage des cas.","Environnement de virtualisation ESXi à deux hôtes administré de façon centralisée par vCenter.","Laboratoire segmenté réunissant réseau pare-feu, Active Directory, SIEM, outils DFIR et environnement red team.","Boîte à outils Bash modulaire automatisant le durcissement Linux sur six composants selon les recommandations de l’ANSSI."];
const frenchDetails = [
  [["Plateforme cloud-native réalisée en équipe pour des services aux visiteurs.","Déploiement Kubernetes avec Helm, GitOps et ArgoCD.","Chaîne DevSecOps Jenkins et observabilité centralisée."],["Sécuriser le CI/CD sans ralentir les livraisons.","Coordonner plusieurs microservices et contrôles automatisés."],["Plateforme entièrement automatisée avec livraison continue GitOps.","Validation de sécurité sur toute la chaîne de déploiement."]],
  [["Infrastructure Kubernetes automatisée selon les principes DevSecOps, GitOps et IaC.","Provisionnement avec Terraform, Ansible et Helm.","Détection Falco et stack Prometheus, Grafana et Loki."],["Conserver une plateforme reproductible sans augmenter la complexité.","Réduire les faux positifs tout en gardant la visibilité sur les attaques."],["Plateforme Kubernetes sécurisée, automatisée et reproductible.","Déploiements GitOps et supervision centralisée."]],
  [["Honeypot SSH/Telnet Cowrie auto-résilient déployé sur AWS.","Les groupes Auto Scaling remplacent les instances compromises.","Les sessions et commandes sont envoyées vers S3 pour analyse."],["Rendre le honeypot crédible pour les attaquants expérimentés.","Empêcher tout mouvement latéral vers la production."],["Collecte de données comportementales riches sur les attaquants.","Renseignement sur les menaces réinjecté dans la supervision."]],
  [["Déploiement automatisé d’une application Flask sur Ubuntu EC2 avec Ansible.","Création d’AMI préconfigurées avec Packer.","Infrastructure AWS avec ALB, Auto Scaling Group et CloudWatch."],["Orchestrer Ansible, Packer et Terraform dans une même chaîne.","Configurer IAM, contrôles d’état et groupes de sécurité."],["Infrastructure auto-résiliente et application hautement disponible.","Supervision centralisée des performances avec CloudWatch."]],
  [["Déploiement d’une pile IaaS OpenStack complète avec DevStack sur Ubuntu.","Gestion des VM, réseaux, volumes et identités multi-locataires.","Extension avec Kata Containers et déploiement automatisé Kolla Ansible."],["Relier correctement les services OpenStack pour créer un système cohérent.","Travailler dans les limites de ressources d’un laboratoire."],["Cloud OpenStack privé fonctionnel validé par CLI et Horizon.","Maîtrise de plusieurs modèles de déploiement et d’isolation."]],
  [["Les détections GuardDuty transitent vers TheHive via EventBridge, Lambda, S3 et SQS.","Des scripts Python importent les alertes, créent les cas et évitent les doublons.","TheHive, Cortex, MISP et Kibana assurent investigation et visualisation."],["Fiabiliser une chaîne événementielle AWS avec plusieurs services et scripts.","Faire correspondre les niveaux de sévérité et résister aux redémarrages."],["Flux automatisé d’une détection GuardDuty à un cas TheHive trié.","Enrichissement par renseignement sur les menaces et relance systemd."]],
  [["Installation de deux hôtes ESXi, datastores VMFS et machines Linux/Windows.","Déploiement de vCenter Server et inventaire centralisé des hôtes.","Mise en place de services FTP, Web, DNS et SSH."],["Repenser le réseau lors du passage à un réseau ponté.","Configurer VCSA, DNS et l’authentification SSH par clés."],["Cluster ESXi à deux hôtes administré depuis vCenter.","Compréhension pratique de la pile vSphere complète."]],
  [["Pare-feu/routeur pfSense segmentant les mini-laboratoires.","Laboratoire Active Directory, Kali Linux, Splunk et Tsurugi Linux.","Centralisation des journaux et détection côté blue team."],["Isoler blue team, red team et Active Directory sans casser les scénarios.","Alimenter Splunk avec des journaux utiles de tout le laboratoire."],["Environnement réutilisable couvrant attaque, défense, investigation et identité.","Base pour les exercices de détection, DFIR et red team."]],
  [["Outil Bash modulaire pour l’authentification, le système de fichiers, le noyau, le matériel, le réseau et le partitionnement.","Politiques PAM, permissions renforcées, ASLR et protections réseau intégrées.","Versions statique et dynamique des modules avec vérification système."],["Transformer les recommandations ANSSI en remédiations sûres et automatisables.","Préserver la disponibilité en rendant les changements réversibles."],["Boîte à outils de durcissement réutilisable, modulaire et interactive.","Application ponctuelle ou surveillance continue, avec vérification de l’état."]]
];
const Context = createContext();
export function LanguageProvider({children}) { const [language,setLanguage] = useState(() => localStorage.getItem("portfolio-language") || "en"); useEffect(() => { document.documentElement.lang = language; localStorage.setItem("portfolio-language", language); }, [language]); const value = useMemo(() => ({ language, setLanguage, t:language === "fr" ? fr : en, personal:language === "fr" ? frenchPersonal : englishPersonal, navLinks:language === "fr" ? englishNavLinks.map((x,i)=>({...x,label:frenchNav[i]})) : englishNavLinks, education:language === "fr" ? englishEducation.map(x=>({...x,degree:"Diplôme d’ingénieur",field:"Cyberdéfense et systèmes de télécommunications embarqués",description:"Formation d’ingénierie couvrant la sécurité réseau, les systèmes embarqués, la cryptographie, les architectures cloud et les méthodologies avancées de cybersécurité."})) : englishEducation, experience:language === "fr" ? englishExperience.map((x,i)=>({...x,role:"Stagiaire en cybersécurité",type:"Stage",projectTitle:i ? "Mise en œuvre d’une solution de prévention des pertes de données" : "Conception et mise en œuvre d’un SIEM Wazuh",description:i ? "Création d’une plateforme automatisée de prévention des pertes de données (DLP) avec OpenDLP, Python, Selenium et un moteur de classification basé sur l’IA." : "Conception et déploiement d’une plateforme SIEM enrichie par l’IA avec Wazuh, règles de détection, moteur UEBA, haute disponibilité SQL Server et alertes automatisées."})) : englishExperience, skillGroups:language === "fr" ? englishSkillGroups.map(x=>({...x,label:({"cloud-infrastructure":"Cloud et infrastructure","containers-orchestration":"Conteneurs et orchestration","devops-gitops-cicd":"DevOps / GitOps / CI-CD","security-devsecops":"Sécurité (DevSecOps / cybersécurité)","soc-siem-threat-intel":"SOC / SIEM / renseignement sur les menaces",observability:"Observabilité","development-scripting":"Développement / scripting","systems-networking":"Systèmes et réseau"})[x.id] || x.label})) : englishSkillGroups, projects:language === "fr" ? englishProjects.map((x,i)=>({...x,title:frenchTitles[i],short:frenchShorts[i],full:frenchDetails[i][0],challenges:frenchDetails[i][1],results:frenchDetails[i][2]})) : englishProjects }),[language]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export const useLanguage = () => useContext(Context);
